# Generated by Django 5.0.7 on 2024-07-21 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime(2024, 7, 21, 8, 22, 38, 37163, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
