# Generated by Django 5.0.7 on 2024-07-21 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 9, 27, 48, 51628, tzinfo=datetime.timezone.utc)),
        ),
    ]
