# Generated by Django 5.0.7 on 2024-07-22 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('sports', 'sports'), ('entertainment', 'entertainment'), ('politics', 'politics'), ('currentaffair', 'currentaffair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 9, 27, 31, 513237, tzinfo=datetime.timezone.utc)),
        ),
    ]
