# Generated by Django 5.0.7 on 2024-07-22 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_news_author_alter_news_category_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='fulldescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 9, 36, 33, 84422, tzinfo=datetime.timezone.utc)),
        ),
    ]
